### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by Innan666** [Stick-To/Object-Detection-API-Tensorflow#20]
def dataset2tfrecord(xml_dir, img_dir, output_dir, name, total_shards=5):
请问这里的total_shards是什么参数，如果我只训练识别一个东西，这里应该设置多少

**Comment by Stick-To** [comment]
这个shard是关于数据集大小的参数， 数据集大可以分片生成多个tfrecord, shard就是个数

**Comment by Innan666** [comment]
W tensorflow/core/framework/op_kernel.cc:1401] OP_REQUIRES failed at fused_batch_norm_op.cc:574 : Resource exhausted: OOM when allocating tensor with shape[15,48,48,256] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[15,48,48,256] and type float
on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
请问刚在训练的时候出现了这种错误是什么原因

**Comment by Stick-To** [comment]
out of memory， 显存溢出

**Comment by Innan666** [comment]
请问这个问题怎么解决呢

**Comment by Stick-To** [comment]
减小batch size 或者用更高级显卡

**Comment by Innan666** [comment]
>> iters 1002/1002 loss nan.6006
>> mean loss nan
./centernet does not exist, create it done
save latest model in ./centernet/test successfully
------------------------- epoch 1 -------------------------
>> iters 1002/1002 loss nan
>> mean loss nan
save latest model in ./centernet/test successfully
------------------------- epoch 2 -------------------------
>> iters 567/1002 loss nan
提了您的方法可以正常训练了，但是经过一个epoch后loss 变成nan了是什么原因 有影响么？

**Comment by Stick-To** [comment]
当然有影响， 可能需要预训练， 试试官方版本

**Comment by Innan666** [comment]
Cannot batch tensors with different shapes in component 1. First element had shape [15,5] and element 2 had shape [17,5].
我在改了几个参数后出现这个错误
我的图片原始尺寸是480*640我改的参数是》
config = {                             
    'input_size': 480,
image_augmentor_config = {
    'output_shape': [480, 640],
    'zoom_size': [400, 400],
trainset_provider = {
    'data_shape': [480, 640, 3],
如过我的全是图片尺寸是480*640我该如何正确设置这些输入输出参数呢

**Comment by Innan666** [comment]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Need minval < maxval, got 0 >= -80
还有个这个问题
