### ISSUE TITLE
checkpoint

### ISSUE THREAD

**Issue by Innan666** [Stick-To/Object-Detection-API-Tensorflow#21]
您好，如果训练意外中断，如何加载checkpoint

**Comment by Stick-To** [comment]
load_weight

**Comment by Innan666** [comment]
load_weight了以后不知道为什么他跑的特别慢，iters跳的比之前慢了好多几乎是卡住了，但是还在跑

**Comment by Stick-To** [comment]
这个不知道，可能是没用GPU

**Comment by Innan666** [comment]
2019-07-11 11:48:07.518860: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
应该是的，但是之前训练时用的呀，您知道怎么解决么

**Comment by Innan666** [comment]
哦解决了 我把上面的# os.environ['CUDA_VISIBLE_DEVICES'] = '2'注释掉就可以了

**Comment by Innan666** [comment]
楼主有没兴趣把CornerNet-Lite搞出来 据说速度精度都高于yolov3


发自我的iPhone

------------------ Original ------------------

**Comment by Stick-To** [comment]
目前没有呢
